// typescript/benchmarks/remix3-fw/app/routes/big.tsx
import { useLoaderData } from "react-router";

function buildRows(count = 400) {
  return Array.from({ length: count }, (_, i) => ({
    id: i + 1,
    value: `row-${i + 1}-${(i * 37) % 101}`,
  }));
}

export async function loader() {
  return { rows: buildRows() };
}

export default function BigPage() {
  const data = useLoaderData() as { rows: Array<{ id: number; value: string }> };
  return (
    <main>
      <h1>Big Payload</h1>
      <ul>
        {data.rows.map((row) => (
          <li key={row.id}>{row.value}</li>
        ))}
      </ul>
    </main>
  );
}

// typescript/benchmarks/sveltekit-app/src/routes/big/+page.svelte
<script lang="ts">
  let { data } = $props();
</script>

<svelte:head>
  <title>Big Table</title>
</svelte:head>

<main>
  <h1>Big Table ({data.rows.length} rows)</h1>
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Value</th>
        <th>Active</th>
      </tr>
    </thead>
    <tbody>
      {#each data.rows as row (row.id)}
        <tr>
          <td>{row.id}</td>
          <td>{row.name}</td>
          <td>{row.value}</td>
          <td>{row.active ? "Yes" : "No"}</td>
        </tr>
      {/each}
    </tbody>
  </table>
</main>
